
package ProyectoHH;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Point;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Camilo
 */
public class HungryHorses extends javax.swing.JFrame {

    private int filas = 8;
    private int columnas = 8;
    int k =1;
    int[][] Matriz = new int[8][8];
    int nivel = 0, contador = 0, ax = 0, ay = 0;
    double ptsBlanco = 0.0, ptsNegro = 0.0;
    String txtJugadas = "";
    Point[] punt = null; //posiciones
    Estado raiz = Estado.crearEstadoInicial(filas);
    Estado Nuevo;
    
    //Iconos Tablero
    private CeldasTablero tablero[][];
    private ImageIcon arregloDeImagenes[] = new ImageIcon[6];

    public HungryHorses() {
        //super("Hungry Horses 1.0.");
        initComponents();
      
        //NIveles:
        cbDificultad.addItem("");
        cbDificultad.addItem("Facil");
        cbDificultad.addItem("Medio");
        cbDificultad.addItem("Dificil");

        this.setVisible(true);
        this.setLocationRelativeTo(null);
        bJugador2.setEnabled(false);
        
        //Imagenes Tablero 
        
        arregloDeImagenes[0] = new ImageIcon(this.getClass().getResource("/imagenes/casillaVacia.png"));
        arregloDeImagenes[1] = new ImageIcon(this.getClass().getResource("/imagenes/caballoBlancoNormal.png"));
        arregloDeImagenes[2] = new ImageIcon(this.getClass().getResource("/imagenes/caballoNegroNormal.png"));
        arregloDeImagenes[3] = new ImageIcon(this.getClass().getResource("/imagenes/cespedNormal.png"));
        arregloDeImagenes[4] = new ImageIcon(this.getClass().getResource("/imagenes/florNormal.png"));
        arregloDeImagenes[5] = new ImageIcon(this.getClass().getResource("/imagenes/manzanaNormal.png"));
        
        tablero = new CeldasTablero[filas][columnas];

       
        crearTablero(raiz.getTablero());
        bJugador2.setEnabled(false);
    }

    public void crearTablero(int[][] matriz) {

        pTablero.removeAll();
        pTablero.setLayout(new GridLayout(filas, columnas));       
        for (int x=0;x<filas;x++){
            for(int y=0; y<columnas;y++){
                 tablero[x][y] = new CeldasTablero();
                 tablero[x][y].setIcon(retornarImagen(matriz[x][y]));
                 tablero[x][y].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                 tablero[x][y].setBorder(BorderFactory.createLineBorder(Color.black));

                 pTablero.add(tablero[x][y]);
            }
        pTablero.updateUI();
        }
        
    }
    
    private Icon retornarImagen(int pos){

        switch(pos){
            case 0: 
                return arregloDeImagenes[0];      
            case 1:
                return arregloDeImagenes[1];   
            case 2:
                return arregloDeImagenes[2];
            case 3:
                return arregloDeImagenes[3];
            case 4:
                return arregloDeImagenes[4];
            case 5:
                return arregloDeImagenes[5];
            default:
                return arregloDeImagenes[0];
          
        }
    }
    /**
     * Creates new form HungryHorses
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lPuntajeJugador1 = new javax.swing.JLabel();
        lImagenJugador1 = new javax.swing.JLabel();
        lPuntaje1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtJugadas = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cbDificultad = new javax.swing.JComboBox<>();
        bJugador1 = new javax.swing.JButton();
        lNivel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lFila = new javax.swing.JLabel();
        jtFila = new javax.swing.JTextField();
        lColumna = new javax.swing.JLabel();
        jtColumna = new javax.swing.JTextField();
        bJugador2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        pTablero = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lPuntajeJugador2 = new javax.swing.JLabel();
        lImagenJugador2 = new javax.swing.JLabel();
        lPuntaje2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lPuntajeJugador1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lPuntajeJugador1.setText("Puntaje jugador #1: ");

        lImagenJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caballoBlancoBoton.png"))); // NOI18N

        lPuntaje1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lPuntaje1.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lImagenJugador1)
                        .addGap(31, 31, 31)
                        .addComponent(lPuntaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lPuntajeJugador1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPuntajeJugador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lImagenJugador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPuntaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtJugadas.setColumns(20);
        jtJugadas.setRows(5);
        jScrollPane1.setViewportView(jtJugadas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
        );

        bJugador1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        bJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caballoBlancoBoton.png"))); // NOI18N
        bJugador1.setText("Jugador 1");
        bJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugador1ActionPerformed(evt);
            }
        });

        lNivel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lNivel.setText("Dificultad: ");

        lFila.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lFila.setText("Fila");

        lColumna.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lColumna.setText("Columna");

        bJugador2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        bJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caballoNegroBoton.png"))); // NOI18N
        bJugador2.setText("Jugador 2");
        bJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugador2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lColumna)
                    .addComponent(lFila))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtFila)
                    .addComponent(jtColumna))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(bJugador2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lFila))
                .addGap(12, 12, 12)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lColumna)
                    .addComponent(jtColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(bJugador2))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDificultad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lNivel)
                                .addGap(0, 109, Short.MAX_VALUE))))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(bJugador1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(bJugador1)
                .addGap(32, 32, 32)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pTablero.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Tablero de Juego", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        pTablero.setToolTipText("");
        pTablero.setPreferredSize(new java.awt.Dimension(320, 320));

        javax.swing.GroupLayout pTableroLayout = new javax.swing.GroupLayout(pTablero);
        pTablero.setLayout(pTableroLayout);
        pTableroLayout.setHorizontalGroup(
            pTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        pTableroLayout.setVerticalGroup(
            pTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lPuntajeJugador2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lPuntajeJugador2.setText("Puntaje Jugador #2: ");

        lImagenJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caballoNegroBoton.png"))); // NOI18N

        lPuntaje2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lPuntaje2.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lImagenJugador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lPuntaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(lPuntajeJugador2)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lPuntajeJugador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lImagenJugador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPuntaje2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Items:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 11))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cespedReducido.png"))); // NOI18N
        jLabel1.setText("Cesped = 1 punto");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/manzanaReducido.png"))); // NOI18N
        jLabel3.setText("Manzana = 5 puntos");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/florReducido.png"))); // NOI18N
        jLabel2.setText("Flor = 3 puntos");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugador2ActionPerformed
        bJugador2.setEnabled(false);
        if ((Double.parseDouble(lPuntaje1.getText()) + Double.parseDouble(lPuntaje2.getText())) < 39) {

            if ((jtFila.getText().length() == 0) || (jtColumna.getText().length() == 0)) {
                JOptionPane.showMessageDialog(null, "ingresar fila y columna para jugar");
            } else {
                String ex = jtFila.getText();
                String ey = jtColumna.getText();
                int entradax = Integer.parseInt(ex);
                int entraday = Integer.parseInt(ey);
                boolean val = false;

                for (int i = 0; i < punt.length; i++) {
                    Point nuevop = punt[i];
                    int axs = (int) nuevop.getX();
                    int ays = (int) nuevop.getY();

                    if ((entradax == axs) && (entraday == ays)) {
                        ax = axs;
                        ay = ays;
                        val = true;
                    }
                }

                if (val) {

                    Point movidanueva = new Point(ax, ay);
                    raiz = Nuevo.resultado(movidanueva);
                    if (raiz.getPuntosNegro() == 3) {
                        ptsNegro = ptsNegro + 3;
                    } else {
                        ptsNegro = ptsNegro + raiz.getPuntosNegro();
                    }

                    lPuntaje2.setText(Double.toString(ptsNegro));
                    crearTablero(raiz.getTablero());      
                    jtFila.setText("");
                    jtColumna.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Jugada no valida !No sea Bruto","ERROR",  
                    JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/error.png"));
                }

            }
        } else {
            jtJugadas.append("MIlagro, Se acabo! " + ptsBlanco + " ------- " + ptsNegro);
            String estadoJuego;
            if (ptsBlanco < ptsNegro) {
                estadoJuego = "Eres Grande,Ganaste!";
            } else {
                estadoJuego = "Sigue Intendandolo, Perdiste! Malo!";
            }
            JOptionPane.showMessageDialog(null, "... por fin!!! " + estadoJuego , "REPORTE",  
                    JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/reporte.png"));
        }

        bJugador1.setEnabled(true);
    }//GEN-LAST:event_bJugador2ActionPerformed

    private void bJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugador1ActionPerformed
        bJugador1.setEnabled(false);
        if ((Double.parseDouble(lPuntaje1.getText()) + Double.parseDouble(lPuntaje2.getText())) < 39) {
        jtFila.setText("");
        jtColumna.setText("");
       
        if (cbDificultad.getSelectedItem() == "Principiante") {        nivel = 2;    } 
        else if (cbDificultad.getSelectedItem() == "Amateur") {        nivel = 4;    } 
        else if (cbDificultad.getSelectedItem() == "Experto") {        nivel = 6;    }
        
        Minimax mov = new Minimax(raiz);
        mov.decisionMax(raiz, nivel);
        Point movida = mov.getMovida();
        Nuevo = raiz.resultado(movida);
        ptsBlanco = ptsBlanco + Nuevo.getPuntosB();
        String puntosBlanco = Double.toString(ptsBlanco);
        lPuntaje1.setText(puntosBlanco);
       
        crearTablero(Nuevo.getTablero());
        
        Minimax mov1 = new Minimax(Nuevo);
        punt = mov1.decisionMin(Nuevo, nivel);
        Point movida1 = mov1.getMovida();
        
        jtJugadas.append( "Jugada "+k+"\n"+"\n");
        for (int i = 0; i < punt.length; i++) {
            Point nuevop = punt[i];
            int ax = (int) nuevop.getX();
            int ay = (int) nuevop.getY();
        
            txtJugadas = "[" + ax + "," + ay + "]";
            jtJugadas.append("la jugadas son: " + txtJugadas + "\n");
          }
            jtJugadas.append("\n"+ "--------------------------------------------"+ "\n");
            k+=1;
        }
        else {
            jtJugadas.append("fin " + ptsBlanco + " ------- " + ptsNegro);
            
            String estadoJuego;
            if (ptsBlanco < ptsNegro) {
                estadoJuego = "Eres Grande, Ganastes!";
            } else {
                estadoJuego = "Sigue intentandolo, Perdiste!";
            }
            JOptionPane.showMessageDialog(null, "... Por fin termino! " + estadoJuego ,"REPORTE",  
                    JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/imagenes/estadoJuego.png"));
        }
        bJugador2.setEnabled(true);
    }//GEN-LAST:event_bJugador1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HungryHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HungryHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HungryHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HungryHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HungryHorses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bJugador1;
    private javax.swing.JButton bJugador2;
    private javax.swing.JComboBox<String> cbDificultad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtColumna;
    private javax.swing.JTextField jtFila;
    public static javax.swing.JTextArea jtJugadas;
    private javax.swing.JLabel lColumna;
    private javax.swing.JLabel lFila;
    private javax.swing.JLabel lImagenJugador1;
    private javax.swing.JLabel lImagenJugador2;
    private javax.swing.JLabel lNivel;
    private javax.swing.JLabel lPuntaje1;
    private javax.swing.JLabel lPuntaje2;
    private javax.swing.JLabel lPuntajeJugador1;
    private javax.swing.JLabel lPuntajeJugador2;
    private javax.swing.JPanel pTablero;
    // End of variables declaration//GEN-END:variables
}
