package ProyectoHH;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Point;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Camilo
 */
public class HungryHorses extends javax.swing.JFrame {

    private int filas = 8;
    private int columnas = 8;
    int k = 1;
    int[][] Matriz = new int[8][8];
    int nivel = 0, contador = 0, ax = 0, ay = 0;
    double ptsBlanco = 0.0, ptsNegro = 0.0;
    String txtJugadas = "";
    Point[] punt = null; //posiciones
    Estado raiz = Estado.crearEstadoInicial(filas);
    Estado Nuevo;
    boolean band = false;

    //Iconos Tablero
    private CeldasTablero tablero[][];
    private ImageIcon arregloDeImagenes[] = new ImageIcon[6];

    public HungryHorses() {
        //super("Hungry Horses 1.0.");
        initComponents();

        //NIveles:
        cbDificultad.addItem("Seleccione Dificultad");
        cbDificultad.addItem("Principiante");
        cbDificultad.addItem("Amateur");
        cbDificultad.addItem("Experto");

        this.setVisible(true);
        this.setLocationRelativeTo(null);
        bJugador2.setEnabled(false);
        jCBoxFila.setEnabled(false);
        jCBoxColumna.setEnabled(false);

        //Imagenes Tablero 
        arregloDeImagenes[0] = new ImageIcon(this.getClass().getResource("/imagenes/casillaVacia.png"));
        arregloDeImagenes[1] = new ImageIcon(this.getClass().getResource("/imagenes/caballoBlancoCasilla.png"));
        arregloDeImagenes[2] = new ImageIcon(this.getClass().getResource("/imagenes/caballoNegroCasilla.png"));
        arregloDeImagenes[3] = new ImageIcon(this.getClass().getResource("/imagenes/cespedCasilla.png"));
        arregloDeImagenes[4] = new ImageIcon(this.getClass().getResource("/imagenes/florCasilla.png"));
        arregloDeImagenes[5] = new ImageIcon(this.getClass().getResource("/imagenes/manzanaCasilla.png"));

        tablero = new CeldasTablero[filas][columnas];

        crearTablero(raiz.getTablero());
        bJugador2.setEnabled(false);
    }

    public void crearTablero(int[][] matriz) {

        pTablero.removeAll();
        pTablero.setLayout(new GridLayout(filas, columnas));
        for (int x = 0; x < filas; x++) {
            for (int y = 0; y < columnas; y++) {
                tablero[x][y] = new CeldasTablero();
                tablero[x][y].setIcon(retornarImagen(matriz[x][y]));
                tablero[x][y].setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                tablero[x][y].setBorder(BorderFactory.createLineBorder(Color.black));

                pTablero.add(tablero[x][y]);
            }
            pTablero.updateUI();
        }

    }

    private Icon retornarImagen(int pos) {

        switch (pos) {
            case 0:
                return arregloDeImagenes[0];
            case 1:
                return arregloDeImagenes[1];
            case 2:
                return arregloDeImagenes[2];
            case 3:
                return arregloDeImagenes[3];
            case 4:
                return arregloDeImagenes[4];
            case 5:
                return arregloDeImagenes[5];
            default:
                return arregloDeImagenes[0];

        }
    }

    public boolean verDificultad() {
        if (cbDificultad.getSelectedItem() == "Seleccione Dificultad") {
            return false;
        } else {
            return true;
        }
    }

    /**
     * Creates new form HungryHorses
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtJugadas = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cbDificultad = new javax.swing.JComboBox<>();
        bJugador1 = new javax.swing.JButton();
        lNivel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lFila = new javax.swing.JLabel();
        lColumna = new javax.swing.JLabel();
        bJugador2 = new javax.swing.JButton();
        jCBoxFila = new javax.swing.JComboBox<>();
        jCBoxColumna = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        pTablero = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lPuntajeJugador1 = new javax.swing.JLabel();
        lImagenJugador1 = new javax.swing.JLabel();
        lPuntaje1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lPuntajeJugador2 = new javax.swing.JLabel();
        lImagenJugador2 = new javax.swing.JLabel();
        lPuntaje2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtJugadas.setColumns(20);
        jtJugadas.setRows(5);
        jScrollPane1.setViewportView(jtJugadas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cbDificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDificultadActionPerformed(evt);
            }
        });

        bJugador1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        bJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caballoBlancoBoton.png"))); // NOI18N
        bJugador1.setText("Jugador 1");
        bJugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugador1ActionPerformed(evt);
            }
        });

        lNivel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lNivel.setText("Dificultad: ");

        lFila.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lFila.setText("Fila");

        lColumna.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lColumna.setText("Columna");

        bJugador2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        bJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caballoNegroBoton.png"))); // NOI18N
        bJugador2.setText("Jugador 2");
        bJugador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugador2ActionPerformed(evt);
            }
        });

        jCBoxFila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione fila", "0", "1", "2", "3", "4", "5", "6", "7" }));
        jCBoxFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBoxFilaActionPerformed(evt);
            }
        });

        jCBoxColumna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione columna", "0", "1", "2", "3", "4", "5", "6", "7" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lFila)
                    .addComponent(lColumna))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBoxFila, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBoxColumna, 0, 155, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(bJugador2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lFila)
                    .addComponent(jCBoxFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lColumna)
                    .addComponent(jCBoxColumna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bJugador2)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bJugador1)
                    .addComponent(cbDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lNivel)
                        .addGap(93, 93, 93)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bJugador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pTablero.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N
        pTablero.setToolTipText("");
        pTablero.setPreferredSize(new java.awt.Dimension(320, 320));

        javax.swing.GroupLayout pTableroLayout = new javax.swing.GroupLayout(pTablero);
        pTablero.setLayout(pTableroLayout);
        pTableroLayout.setHorizontalGroup(
            pTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        pTableroLayout.setVerticalGroup(
            pTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        jPanel9.setLayout(new java.awt.GridLayout(8, 1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel4.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel4.setName(""); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel9.add(jLabel4);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("1");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel5.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel5.setName(""); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel9.add(jLabel5);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("2");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel6.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel6.setName(""); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel9.add(jLabel6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("3");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel7.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel7.setName(""); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel9.add(jLabel7);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("4");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel8.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel8.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel8.setName(""); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel9.add(jLabel8);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("5");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel9.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel9.setName(""); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel9.add(jLabel9);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("6");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel10.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel10.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel10.setName(""); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel9.add(jLabel10);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("7");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel11.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel11.setName(""); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel9.add(jLabel11);

        jPanel10.setLayout(new java.awt.GridLayout(1, 8));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("0");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel12.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel12.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel12.setName(""); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel10.add(jLabel12);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("1");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel13.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel13.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel13.setName(""); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel10.add(jLabel13);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("2");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel14.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel14.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel14.setName(""); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel10.add(jLabel14);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("3");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel15.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel15.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel15.setName(""); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel10.add(jLabel15);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("4");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel16.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel16.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel16.setName(""); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel10.add(jLabel16);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("5");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel17.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel17.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel17.setName(""); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel10.add(jLabel17);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("6");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel18.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel18.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel18.setName(""); // NOI18N
        jLabel18.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel10.add(jLabel18);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("7");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel19.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel19.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel19.setName(""); // NOI18N
        jLabel19.setPreferredSize(new java.awt.Dimension(25, 35));
        jPanel10.add(jLabel19);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pTablero, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(pTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ítems:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cespedNormal.png"))); // NOI18N
        jLabel1.setText("Cesped = 1 punto");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/manzanaNormal.png"))); // NOI18N
        jLabel3.setText("Manzana = 5 puntos");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/florNormal.png"))); // NOI18N
        jLabel2.setText("Flor = 3 puntos");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Puntuación:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        lPuntajeJugador1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lPuntajeJugador1.setText("Jugador #1: ");

        lImagenJugador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caballoBlancoNormal.png"))); // NOI18N

        lPuntaje1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lPuntaje1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPuntaje1.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lPuntajeJugador1)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lImagenJugador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lPuntaje1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lPuntajeJugador1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lImagenJugador1)
                    .addComponent(lPuntaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lPuntajeJugador2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        lPuntajeJugador2.setText("Jugador #2: ");

        lImagenJugador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/caballoNegroNormal.png"))); // NOI18N

        lPuntaje2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lPuntaje2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPuntaje2.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPuntajeJugador2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lImagenJugador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lPuntaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lPuntajeJugador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lPuntaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lImagenJugador2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bJugador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugador2ActionPerformed
        //bJugador2.setEnabled(false);
        if (verDificultad() == false) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una dificultad");
            bJugador1.setEnabled(true);
        } else {
            if ((Double.parseDouble(lPuntaje1.getText()) + Double.parseDouble(lPuntaje2.getText())) < 39) {

                if ((jCBoxFila.getSelectedItem() == "Seleccione fila") || (jCBoxColumna.getSelectedItem() == "Seleccione columna")) {
                    bJugador1.setEnabled(false);
                    JOptionPane.showMessageDialog(null, "ingresar fila y columna para jugar");
                    bJugador2.setEnabled(true);
                } else {

                    String ex = (String) jCBoxFila.getSelectedItem();
                    String ey = (String) jCBoxColumna.getSelectedItem();
                    jCBoxFila.setSelectedIndex(0);
                    jCBoxColumna.setSelectedIndex(0);

                    int entradax = Integer.parseInt(ex);
                    int entraday = Integer.parseInt(ey);
                    boolean val = false;

                    for (int i = 0; i < punt.length; i++) {
                        Point nuevop = punt[i];
                        int axs = (int) nuevop.getX();
                        int ays = (int) nuevop.getY();

                        if ((entradax == axs) && (entraday == ays)) {
                            ax = axs;
                            ay = ays;
                            val = true;
                            bJugador1.setEnabled(true);
                            cbDificultad.setEnabled(true);
                            bJugador2.setEnabled(false);
                            jCBoxFila.setEnabled(false);
                            jCBoxColumna.setEnabled(false);
                        }
                    }

                    if (val) {

                        Point movidanueva = new Point(ax, ay);
                        raiz = Nuevo.resultado(movidanueva);
                        if (raiz.getPuntosNegro() == 3) {
                            ptsNegro = ptsNegro + 3;
                        } else {
                            ptsNegro = ptsNegro + raiz.getPuntosNegro();
                        }

                        lPuntaje2.setText(Double.toString(ptsNegro));
                        crearTablero(raiz.getTablero());
                        String estadoJuego;
                        if (ptsNegro > 19.0) {
                            estadoJuego = "Ganaste, ha ganado la humanidad y no hay forma de que te supere en puntaje";
                            JOptionPane.showMessageDialog(null, estadoJuego);
                            System.exit(1);
                        }

                        if (ptsBlanco > 19.0) {
                            estadoJuego = "Perdiste, ganan los robots y no hay forma de superarlos en esta partida";
                            JOptionPane.showMessageDialog(null, estadoJuego);
                            System.exit(1);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Jugada invalida, en el area de texto se muestra las posibles jugadas");
                        bJugador1.setEnabled(false);
                    }

                }
            } else {
                jtJugadas.append("El juego termina así: " + ptsBlanco + " ------- " + ptsNegro);
                String estadoJuego;
                if (ptsBlanco < ptsNegro) {
                    estadoJuego = "Ganaste, ha ganado la humanidad";
                } else {
                    estadoJuego = "Perdiste, ganan los robots";
                }
                //JOptionPane.showMessageDialog(null, "... por fin!!! " + estadoJuego);
            }
        }
        //bJugador1.setEnabled(true);
    }//GEN-LAST:event_bJugador2ActionPerformed

    private void bJugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugador1ActionPerformed

        if (verDificultad() == false) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una dificultad");
            bJugador1.setEnabled(true);
        } else {
            bJugador1.setEnabled(false);
            cbDificultad.setEnabled(false);
            if ((Double.parseDouble(lPuntaje1.getText()) + Double.parseDouble(lPuntaje2.getText())) < 39) {

                if (cbDificultad.getSelectedItem() == "Principiante") {
                    nivel = 2;
                    System.out.println("Principiante" + nivel);
                } else if (cbDificultad.getSelectedItem() == "Amateur") {
                    nivel = 4;
                    System.out.println("Amateur" + nivel);
                } else if (cbDificultad.getSelectedItem() == "Experto") {
                    nivel = 6;
                    System.out.println("Experto" + nivel);
                }

                Minimax mov = new Minimax(raiz);
                mov.decisionMax(raiz, nivel);
                Point movida = mov.getMovida();
                Nuevo = raiz.resultado(movida);
                ptsBlanco = ptsBlanco + Nuevo.getPuntosB();
                String puntosBlanco = Double.toString(ptsBlanco);
                lPuntaje1.setText(puntosBlanco);

                crearTablero(Nuevo.getTablero());

                Minimax mov1 = new Minimax(Nuevo);
                punt = mov1.decisionMin(Nuevo, nivel);
                Point movida1 = mov1.getMovida();
                jCBoxFila.setEnabled(true);
                jCBoxColumna.setEnabled(true);
                bJugador2.setEnabled(true);

                String estadoJuego;
                if (ptsNegro > 19.0) {
                    estadoJuego = "Ganaste, ha ganado la humanidad y no hay forma de que te supere en puntaje";
                    JOptionPane.showMessageDialog(null, "... Por fin termino! " + estadoJuego);
                }

                if (ptsBlanco > 19.0) {
                    estadoJuego = "Perdiste, ganan los robots y no hay forma de superarlos en esta partida";
                    JOptionPane.showMessageDialog(null, "... Por fin termino! " + estadoJuego);
                }
                /*if (ptsBlanco < ptsNegro) {
                estadoJuego = "Ganaste, ha ganado la humanidad";
                JOptionPane.showMessageDialog(null, "... Por fin termino! " + estadoJuego);
            } /*else {
                estadoJuego = "Perdiste, ganan los robots";
                JOptionPane.showMessageDialog(null, "... Por fin termino! " + estadoJuego);
            }*/

                jtJugadas.append("Jugada " + k + "\n" + "\n");
                for (int i = 0; i < punt.length; i++) {
                    Point nuevop = punt[i];
                    int ax = (int) nuevop.getX();
                    int ay = (int) nuevop.getY();

                    txtJugadas = "[" + ax + "," + ay + "]";
                    jtJugadas.append("Las jugadas son: " + txtJugadas + "\n");
                }
                jtJugadas.append("\n" + "____________________" + "\n");
                k += 1;
            } else {
                jtJugadas.append("fin " + ptsBlanco + " ------- " + ptsNegro);

                /*String estadoJuego;
            if (ptsNegro == 20){
                estadoJuego = "Ganaste, ha ganado la humanidad y no hay forma de que te supere en puntaje";
            }
            
            if (ptsBlanco == 20){
                estadoJuego = "Perdiste, ganan los robots y no hay forma de superarlos en esta partida";
            }
            if (ptsBlanco < ptsNegro) {
                estadoJuego = "Ganaste, ha ganado la humanidad";
            } else {
                estadoJuego = "Perdiste, ganan los robots";
            }*/
                //JOptionPane.showMessageDialog(null, "... Por fin termino! " + estadoJuego);
            }
            //bJugador2.setEnabled(true);
        }
    }//GEN-LAST:event_bJugador1ActionPerformed

    private void cbDificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDificultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDificultadActionPerformed

    private void jCBoxFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBoxFilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBoxFilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HungryHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HungryHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HungryHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HungryHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HungryHorses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bJugador1;
    private javax.swing.JButton bJugador2;
    private javax.swing.JComboBox<String> cbDificultad;
    private javax.swing.JComboBox<String> jCBoxColumna;
    private javax.swing.JComboBox<String> jCBoxFila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jtJugadas;
    private javax.swing.JLabel lColumna;
    private javax.swing.JLabel lFila;
    private javax.swing.JLabel lImagenJugador1;
    private javax.swing.JLabel lImagenJugador2;
    private javax.swing.JLabel lNivel;
    private javax.swing.JLabel lPuntaje1;
    private javax.swing.JLabel lPuntaje2;
    private javax.swing.JLabel lPuntajeJugador1;
    private javax.swing.JLabel lPuntajeJugador2;
    private javax.swing.JPanel pTablero;
    // End of variables declaration//GEN-END:variables
}
